added accessToken option
watergis/mapbox-gl-export pull request #23
Opened 2021-07-23 15:18 UTC by Sitocp

Thank you for submitting a pull request!

## Description

Added option for accessToken.

## Type of Pull Request

- [X] Adding a feature
- [ ] Fixing a bug
- [ ] Maintaining documents
- [ ] Others ()

## Verify the followings

- [X] Code is up-to-date with the `main` branch
- [ ] No lint errors after `npm run lint`
- [ ] Make sure all the exsiting features working well

2021-07-23 15:46 UTC, JinIgarashi requested changes
@Sitocp Thank you for pull request. The change looks fine. However there is an error in CI, could you fix it? so I can merge and release it.

2021-07-23 15:46 UTC, JinIgarashi commented on lib/map-generator.ts
> +    accessToken?: string,
There is an error. Could you fix it?

2021-07-23 15:51 UTC, JinIgarashi approved these changes
Thank you for fixing quickly!

2021-07-23 15:52 UTC, Sitocp commented
Thank you! ^^

2021-07-24 06:18 UTC, merged

2021-07-24 06:32 UTC, JinIgarashi commented
@Sitocp now [v1.2.9](https://github.com/watergis/mapbox-gl-export/releases/tag/v1.2.9) was released! thanks